spring.data.mongodb.uri=mongodb+srv://omkarpatange77_db_user:mzI5wcEcroxPVyM1@student-management-syst.ggpf2yv.mongodb.net/student_management
server.port=8080
server.port=${PORT:8080}
spring.thymeleaf.cache=false
spring.security.user.name=omkarpatange77@gmail.com
spring.security.user.password=Omkar@3483
spring.security.user.roles=ADMIN